//Program to Read the Root file
#include "TSystem.h"
void Root_File_energy(){
   // read the Tree generated by tree1w and fill two histograms
   // note that we use "new" to create the TFile and TTree objects,
   // to keep them alive after leaving this function.
   TFile *f = new TFile("Electrons.root");
   TTree *t1 = (TTree*)f->Get("ntuple");
   Float_t I_Energy,X_i,Y_i,Z_i,t_i,E_De,X_f,Y_f,Z_f,t_f;
   Float_t total_energy;

   t1->SetBranchAddress("I_Energy",&I_Energy);
   t1->SetBranchAddress("X_i",&X_i);
   t1->SetBranchAddress("Y_i",&Y_i);
   t1->SetBranchAddress("Z_i",&Z_i);
   t1->SetBranchAddress("t_i",&t_i);
   t1->SetBranchAddress("E_De",&E_De);
   t1->SetBranchAddress("X_f",&X_f);
   t1->SetBranchAddress("Y_f",&Y_f);
   t1->SetBranchAddress("Z_f",&Z_f);
   t1->SetBranchAddress("t_f",&t_f);
   // create two histograms
   TH1F *hpx   = new TH1F("hpx","Initial_energy",300,0,0.0084);
   TH1F *hpx_i   = new TH1F("hpx_i","Deposited Energy",100,0,0.0084);
   TH1F *hpt_i  = new TH1F("hpt_i","Phonons_L Distribution Final Time",100,0,8000);
  TH1F *hpx2   = new TH1F("hpx2","Phonons_L Distribution on AL",100,0,0.03);
  TH1F *hpx3   = new TH1F("hpx3","Phonons_L Distribution on Nb",100,0,0.03);
   TH2F *hpxpy = new TH2F("hpxpy"," Initial Position Phonons ",200,-0.06,0.06,200,-0.06,0.06);
   TH2F *hpxpz = new TH2F("hpxpz"," Initial Position Phonons x vs z ",200,-0.06,0.06,200,-0.06,0.06);
   TH3F *XYE_dep = new TH3F("XYE_dep","Energy Distribution",200,-0.02,0.025,300,-0.01,0.01,50,0,20000);
   //read all entries and fill the histograms
   Int_t nentries = (Int_t)t1->GetEntries();
   for (Int_t i=0; i<nentries; i++) {
      t1->GetEntry(i);
      hpx->Fill(I_Energy);
      hpx_i->Fill(I_Energy);
        hpt_i->Fill(t_f);

      total_energy+=I_Energy;

      hpxpy->Fill(X_i,Y_i);
        hpxpy->Fill(X_i,Z_i);
      //hpxpy->Fill(Z_i,I_Energy);


      //hpxpy->Fill(I_Energy,TMath::Sqrt(X_i*X_i+Y_i*Y_i+Z_i*Z_i));
      XYE_dep->Fill(X_i,Y_i,t_f);
if (TMath::Sqrt(X_f*X_f+Y_f*Y_f)<0.071) {

    hpx2->Fill(I_Energy);
}


//Introduce the radius X_f*X_f+Y_f*Y_f<
if (TMath::Sqrt(X_f*X_f+Y_f*Y_f)>0.071) {

    hpx3->Fill(I_Energy);
  }

}



   // We do not close the file. We want to keep the generated
   // histograms we open a browser and the TreeViewer
   // if (gROOT->IsBatch()) return;
   // new TBrowser ();
   // t1->StartViewer();
TF1 *g1 = new TF1("m1","gaus",0,0.06);

   TCanvas *c1 = new TCanvas("c1","c1",600,800);
     // c1->SetFillColor(0);
     //hpx->SetXTitle("Energy eV");
     //hpx->SetYTitle("# of Phonons");

       //hpx->Fit("gaus");

      //   hpx->SetXTitle("Energy eV ");
      // hpx->SetYTitle(" # of Electrons ");
      //   hpx->Draw();
     //      hpx2->Draw("same");
     //      hpx3->Draw("sames");
    //  XYE_dep->Draw("BOX2 Z");
    //  XYE_dep->SetXTitle("X cm ");
    //  XYE_dep->SetYTitle("Y cm ");
    // XYE_dep->SetZTitle("Energy Ev ");
  //   hpxpy->Draw("SURF3");
       hpt_i->Draw();
       hpx_i->SetXTitle("Energy eV");
       hpx_i->SetYTitle("# of Phonons");
       hpxpy->SetXTitle("X cm");
       hpxpy->SetYTitle("Z cm ");
       hpx->SetXTitle("Energy eV");
   //     printf("The total Energy of the System is %f\n",total_energy );
   TCanvas *c2 = new TCanvas("c2","c2",600,800);
     hpx->Draw();

    TCanvas *c3 = new TCanvas("c3","c3",600,1200);


    // t1->Draw("Z_i:X_i:Y_i","t_i>19000 && t_i<20000");
    //
      //  newtree->SetMarkerColor(2);
        //newtree->Draw("Z_i:X_i:Y_i","(I_Energy>0.00031 && I_Energy<0.00042)");
        t1->SetMarkerColor(4);//4 blue 2 Red
        t1->SetMarkerSize(0.4);
    t1->SetMarkerStyle(20);
t1->Draw("Z_i:X_i:Y_i","(I_Energy>0.0 && I_Energy<0.007) && (t_i>0 && t_i<5)");
t1->SetMarkerColor(2);//4 blue 2 Red
t1->SetMarkerSize(0.4);
t1->SetMarkerStyle(20);
t1->Draw("Z_i:X_i:Y_i","(I_Energy>0.007 && I_Energy<0.1) &&( t_i>0 && t_i<5)","same");

//Doing an animated Gift to see the impact of the phonons and the Holes and Electrons

      TCanvas *c4 = new TCanvas("c4","c4",600,800);
       //hpt_i->Draw();
        	char const * A[20]= {"(I_Energy>0.0 && I_Energy<0.007) && (t_i>0 && t_i<5)",
      "(I_Energy>0.0 && I_Energy<0.007) && (t_i>5 && t_i<10)",
    "(I_Energy>0.0 && I_Energy<0.007) && (t_i>10 && t_i<15)",
  "(I_Energy>0.0 && I_Energy<0.007) && (t_i>15 && t_i<20)",
"(I_Energy>0.0 && I_Energy<0.007) && (t_i>20 && t_i<25)",
"(I_Energy>0.0 && I_Energy<0.007) && (t_i>25 && t_i<30)",
"(I_Energy>0.0 && I_Energy<0.007) && (t_i>30 && t_i<35)",
"(I_Energy>0.0 && I_Energy<0.007) && (t_i>35 && t_i<40)",
"(I_Energy>0.0 && I_Energy<0.007) && (t_i>40 && t_i<45)",
"(I_Energy>0.0 && I_Energy<0.007)  && (t_i>45 && t_i<50)",
"(I_Energy>0.0 && I_Energy<0.007)  && (t_i>50 && t_i<55)",
"(I_Energy>0.0 && I_Energy<0.007)  && (t_i>55 && t_i<60)",
"(I_Energy>0.0 && I_Energy<0.007) && (t_i>60 && t_i<65)",
"(I_Energy>0.0 && I_Energy<0.007) && (t_i>65 && t_i<70)",
"(I_Energy>0.0 && I_Energy<0.007)  && (t_i>70 && t_i<75)",
"(I_Energy>0.0 && I_Energy<0.007)  && (t_i>75 && t_i<80)",
"(I_Energy>0.0 && I_Energy<0.007) && (t_i>80 && t_i<85)",
"(I_Energy>0.0 && I_Energy<0.007)  && (t_i>85 && t_i<90)",
"(I_Energy>0.0 && I_Energy<0.007)  && (t_i>90 && t_i<95)","(I_Energy>0.0 && I_Energy<0.007) && (t_i>95 && t_i<100)",};

char const * B[20]= {"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>0 && t_i<5)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>5 && t_i<10)",
"(I_Energy>0.007 && I_Energy<0.1) && (t_i>10 && t_i<15)",
"(I_Energy>0.007 && I_Energy<0.1) && (t_i>15 && t_i<20)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>20 && t_i<25)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>25 && t_i<30)",
"(I_Energy>0.007 && I_Energy<0.1) && (t_i>30 && t_i<35)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>35 && t_i<40)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>40 && t_i<45)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>45 && t_i<50)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>50 && t_i<55)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>55 && t_i<60)",
"(I_Energy>0.007 && I_Energy<0.1) && (t_i>60 && t_i<65)",
"(I_Energy>0.007 && I_Energy<0.1) && (t_i>65 && t_i<70)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>70 && t_i<75)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>75 && t_i<80)",
"(I_Energy>0.007 && I_Energy<0.1) && (t_i>80 && t_i<85)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>85 && t_i<90)",
"(I_Energy>0.007 && I_Energy<0.1)  && (t_i>90 && t_i<95)","(I_Energy>0.007 && I_Energy<0.1)  && (t_i>95 && t_i<100)"};

char const *CC[20]={"tut_1.gif","tut_2.gif","tut_3.gif","tut_4.gif","tut_5.gif","tut_6.gif","tut_7.gif","tut_8.gif","tut_9.gif","tut_10.gif","tut_11.gif","tut_12.gif","tut_13.gif","tut_14.gif","tut_15.gif","tut_16.gif","tut_17.gif","tut_18.gif","tut_19.gif","tut_20.gif"};

//gSystem->Unlink("tut28.gif");
for (int i=0; i<20;i++){

  t1->SetMarkerColor(4);//4 blue 2 Red
  t1->SetMarkerSize(0.4);
t1->SetMarkerStyle(20);
t1->Draw("Z_i:X_i:Y_i",A[i]);
t1->SetMarkerColor(2);//4 blue 2 Red
t1->Draw("Z_i:X_i:Y_i",B[i],"same");
c4->Print(CC[i]);
//c4->Modified();
//c4->Update();


//sleep(1);
}
//c4->Print("tut28.gif");

   //In the browser, click on "ROOT Files", then on "tree1.root"
   //You can click on the histogram icons in the right panel to draw
   //them in the TreeViewer, follow the instructions in the Help.
}
